---
- hosts: "dashboard"
  become: "yes"
  roles:
    - "City-of-Bloomington.mysql"
    - "City-of-Bloomington.php"

  tasks:
    - name: "Install distro packages"
      apt:
        name: "{{ item }}"
        state: "present"
      with_items:
        - "php-mysql"

    - name: "Create mysql database"
      mysql_db:
        config_file: "{{ mysql_defaults_extra_file }}"
        name: "{{ dashboard_db.name }}"
        state: "present"
      no_log: "True"

    - name: "Create mysql user for site"
      mysql_user:
        name:     "{{ dashboard_db.user }}"
        password: "{{ dashboard_db.pass }}"
        priv:     "{{ dashboard_db.name }}.*:ALL"
        state: "present"
        config_file: "{{ mysql_defaults_extra_file }}"
      no_log: "True"

    - name: "Extract release"
      unarchive:
        src: "{{ dashboard_archive_path }}"
        dest: "/usr/local/src"
      register: "release"

    - name: "Remove old release"
      file:
        path: "{{ dashboard_install_path }}"
        state: "absent"
      when: "release.changed"

    - name: "Create directories"
      file:
        path: "{{ item }}"
        state: "directory"
        owner: "www-data"
        group: "staff"
        mode:  "u=rwX,g=rwXs,o=rX"
      with_items:
        - "{{ dashboard_install_path }}"
        - "{{ dashboard_backup_path  }}"
        - "{{ dashboard_site_home    }}"
        - "/var/log/cron"

    - name: "Install release"
      command: "rsync -rl /usr/local/src/dashboard/ {{ dashboard_install_path }}/"
      when: "release.changed"

    - name: "Update site_home"
      command: "rsync -rl /usr/local/src/dashboard/data/ {{ dashboard_site_home }}/"
      when: "release.changed"

    - name: "Apache configuration"
      template:
        src:  "apache.conf"
        dest: "/etc/apache2/sites-enabled/conf.d/dashboard.conf"
      notify: "apache_restart"

    - name: "Install CRON"
      template:
        src:  "cron.sh"
        dest: "/etc/cron.daily/backup.d/dashboard"
        mode: "0755"

    - name: "Configure backup credentials"
      template:
        src:  "backup.cnf"
        dest: "/etc/cron.daily/backup.d/dashboard.cnf"
        mode: "0400"

    - name: "Install site_config"
      template:
        src:  "site_config.inc"
        dest: "{{ dashboard_site_home }}/site_config.inc"

    - name: "Update directory ownership"
      command: "chown -R www-data:staff {{ item }}"
      args:
        warn: "no"
      with_items:
        - "{{ dashboard_install_path }}"
        - "{{ dashboard_backup_path  }}"
        - "{{ dashboard_site_home    }}"

    - name: "Update directory permission"
      command: "chmod -R u=rwX,g=rwX,o=rX {{ item }}"
      args:
        warn: "no"
      with_items:
        - "{{ dashboard_install_path }}"
        - "{{ dashboard_backup_path  }}"
        - "{{ dashboard_site_home    }}"
...
